MIC-TEAM/miccha-front

README.md
pull request 테스트를 위한 README 파일 생성
-> 추후 README 파일 내용 보완하겠습니다
=> README 파일 생성

src/pages/index.tsx
=> [mic-002] PR 테스트를 위한 수정

src/pages/_app.tsx, src/pages/_document.tsx, src/utils/GlobalStyles.tsx
[mic-003] 메타 태그 적용 및 글로벌 폰트 적용
https://github.com/MIC-TEAM/miccha-front/projects/1
=> [mic-003] 메타 태그 적용 및 글로벌 폰트 적용

package.json, src/lib/apiClient.ts, yarn.lock
[mic-004] axios 모듈화 작업
https://github.com/MIC-TEAM/miccha-front/projects/1
=> [mic-004] axios 모듈화 작업

package.json, src/components/Main/index.tsx, src/components/Main/styles.tsx, src/pages/index.tsx, src/pages/styles.tsx, yarn.lock
=> [mic-006] fix : main page Scrolling 작업완료

src/components/Main.tsx
로그인 전 시작 페이지 버튼명 수정했습니다!
[2주 무료 시작하기] -> [MICCHA 시작하기]
=> [Mic 015] 로그인 전 시작 페이지 버튼명 수정

src/components/Main.tsx, src/components/common/Header.tsx
헤더 버튼과 링크 이동 재사용성을 위해 props 적용하였습니다!
=> [Mic 016] 헤더 Props 적용

src/components/common/SubmitButton.tsx
좋은 리뷰 감사합니당 !
type 기본값 설정해서 반영하였습니다~😄
=> [mic-007] fix : type default 설정

src/recoil/home_movies/atom.ts, src/recoil/home_movies/index.ts
recoil 환경 세팅 및 Home Movies atom 세팅 진행하였습니다-!
=> [mic-023] recoil 환경 세팅 및 Home Movies atom 세팅

public/images/common/sliderArr_left.svg, public/images/common/sliderArr_right.svg, src/components/home/MovieSlider.tsx, src/pages/home.tsx, src/styles/home_movie.ts, src/styles/movie.ts
영화목록 슬라이더 마우스 호버했을 때 화살표 처리 작업 완료했습니다! 😁
=> [mic-028] fix: movieSlider 화살표 작업완료

src/pages/home.tsx, src/styles/global-styles.tsx
- home 페이지 background-color 미적용 이슈 수정하였습니다.
=> [MIC-029] home 페이지 background-color 미적용 이슈 수정

src/components/home/MovieItem.tsx
Slider Item 호버시 콘텐츠 나오게 작업중입니다. 확인 부탁드립니다 😁
=> fix: movie 슬라이더 아이템 작업중

src/components/reset_password/Form.tsx, src/pages/reset_password.tsx, src/styles/global-styles.tsx
- 비밀번호 변경 페이지 마크업
- ResetPasswordForm 컴포넌트 분리 작업
완료하였습니다! 확인 부탁드리겠습니다~!
=> [mic-030] 비밀번호 변경 페이지 마크업

src/hooks/useSignUp.ts, src/lib/apiClient.ts, src/pages/sign_up.tsx, src/recoil/home_movies/selector.ts
- 회원가입 기능 api 연동
- 중복 이메일, 형식에 맞지 않는 이메일 검증 기능 추가
작업하였습니다! 확인 부탁드립니다~!
=> [mic-029] 회원가입 기능 api 연동

src/components/FindPasswordForm.tsx, src/components/common/ValidationError.tsx, src/hooks/useFindPasswordForm.ts, src/pages/sign_up.tsx, src/styles/sign_up.ts
- 패스워드 찾기 api 연동
- 중복되는 Validation Error 문구 공통 컴포넌트화 진행하였습니다
리뷰 부탁드립니다!
=> [mic-033] 비밀번호 찾기 기능 구현

src/components/FindPasswordForm.tsx, src/hooks/useFindPasswordForm.ts, src/utils/error-code.ts
1. 에러 코드 추가
2. 가입되지 않은 비밀번호 요청시 오류 메세지 기능 구현
리뷰 부탁드립니다!
=> [mic-038] 비밀번호 찾기 페이지 에러 코드 추가 및 리팩토링

src/components/reset_password/Form.tsx, src/hooks/useResetPasswordForm.ts, src/pages/reset_password/[token].tsx
=> [mic-036] 새로운 비밀번호 설정 페이지 구현

src/hooks/useAuth.ts, src/lib/apiClient.ts
- 로그인 처리를 위한 ajax 설정 세팅
백엔드 로그인 api 구현시 추가 기능 구현 진행하겠습니다~!
=> [mic-039] 로그인 처리를 위한 ajax 설정 세팅

src/components/common/HomeHeader.tsx, src/pages/header.tsx, src/styles/home_movie.ts
로그인 성공 했을 때에 header 작업 중 입니당 !
남은 작업은 집에 가서 하도록 하겠습니다 :)
=> add : 로그인 성공시의  header

package.json, src/components/home/MovieMain.tsx, src/pages/home.tsx, src/styles/home_movie.ts, yarn.lock
홈 페이지 메인 슬라이더 작업 완료 했습니다.
Swiper 플러그인을 사용하여 구현하였고,
제목, 줄거리, 버튼 작업은 오늘 안으로 작업하겠습니다.
코드리뷰 요청드립니다 감사합니다 😊
=> add : home movie main slider

src/components/FindPasswordForm.tsx, src/components/common/SubmitButton.tsx, src/components/sign_in/LoginForm.tsx, src/hooks/useLoginForm.ts, src/recoil/user/atom.ts
- 로그인 기능 구현하였습니다
- 토근 재발급 기능, 로그인 되었는지 검사 기능은 백엔드 api 구현되는 대로 작업하겠습니다
=> [mic-045] 로그인 기능 api 연동 작업

src/components/common/HomeHeader.tsx, src/components/home/MovieShow.tsx, src/styles/home_movie.ts
=> [mic-047] add : home 헤더 스크롤시 검정바 구현

.vscode/extensions.json, src/components/common/HomeHeader.tsx, src/components/home/MovieShow.tsx, src/styles/home_header.ts, src/styles/home_movie.ts
`탐색하기` 메뉴 컴포넌트 마크업 작업 완료했습니다.
먼저 카테고리 api 작업해 주시면,
그 후에 스타일 작업과 마우스오버 이벤트 작업 하도록 하겠습니다~
=> [Mic-048] 탐색하기 메뉴 컴포넌트 마크업 작업

src/components/home/MovieSlider.tsx
=> [mic-054] fix : 슬라이드 화살표

src/components/common/Footer.tsx, src/components/home/MovieSlider.tsx
=> [mic-051] 슬라이더 버튼 

src/components/home/MovieSlider.tsx
무비 슬라이드 동작 구현 완료했습니다~
리뷰 부탁드립니다!
=> [mic-060] 무비 슬라이드 동작 구현

src/components/settings/SettingButton.tsx, src/components/settings/SettingTitle.tsx, src/pages/settings/email.tsx, src/pages/settings/password.tsx
setting 페이지 컴포넌트 구조 리팩토링 완료했습니다
리뷰 부탁드려요~!
=> [mic-064] setting 페이지 컴포넌트 구조 리팩토링

src/components/common/HomeHeader/SearchBox.tsx, src/components/common/HomeHeader/index.tsx, src/components/home/MovieMain.tsx, src/components/home/MovieShow.tsx, src/pages/search.tsx
검색 기능 구현했습니다
리뷰 부탁드립니다!
홈, 탐색하기, 검색 페이지 내에 HomeHeader 컴포넌트를 각각 import 하는 방식으로 설계해서 실시간 검색 기능 구현이 힘들게 되었습니다ㅠ
다음 프로젝트는 공통으로 사용하는 헤더는 Layout 컴포넌트를 따로 만들어 적용해야할 것 같습니다~!
=> [mic-064] 검색 기능 구현

src/components/common/HomeHeader/styles.ts, src/components/home/ItemHover.tsx, src/components/home/MovieDetail.tsx, src/components/home/MovieItem.tsx, src/components/home/MovieShow.tsx, src/components/home/MovieSlider.tsx, src/components/settings/SettingButton.tsx, src/pages/search.tsx, src/pages/settings/index.tsx, src/pages/wishes.tsx
반응형 디바이스 아이패드 에어 기준과 아이폰 X 기준 작업 완료했습니다~
확인 부탁드립니다 감사합니다 :)
=> [MIC-067] 반응형 작업 (768, 414px 기준)

src/components/common/Footer.tsx, src/components/common/HomeHeader/GenreMenu.tsx, src/components/common/HomeHeader/MyMenu.tsx, src/components/common/HomeHeader/index.tsx, src/components/common/HomeHeader/styles.ts, src/pages/settings/email.tsx, src/pages/settings/index.tsx, src/pages/settings/password.tsx
헤더 유저 이름 마우스 호버 시 설정페이지, 로그아웃 모달창 작업 완료했습니다!
그리고 이전에 이슈 있었던 footer 부분도 수정했습니다.
확인 부탁드립니다 감사합니다 :)
=> [mic-066] add : 유저이름 마우스 호버 시 모달창
